// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGG60FR0bNFupLebZxgsbreT2LUVXl6V0',
    appId: '1:64305981522:web:5546bb246a19a8f8e8d78b',
    messagingSenderId: '64305981522',
    projectId: 'taskify-cb192',
    authDomain: 'taskify-cb192.firebaseapp.com',
    storageBucket: 'taskify-cb192.firebasestorage.app',
    measurementId: 'G-8F25XQP8RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9_kynqHSpFARntcFQkHNcyD2Si4NxrU',
    appId: '1:64305981522:android:1e655d028830cfd5e8d78b',
    messagingSenderId: '64305981522',
    projectId: 'taskify-cb192',
    storageBucket: 'taskify-cb192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC35XOguJdRr0O918kYLqrXhOCc42hUW-Y',
    appId: '1:64305981522:ios:986443b71ee204d5e8d78b',
    messagingSenderId: '64305981522',
    projectId: 'taskify-cb192',
    storageBucket: 'taskify-cb192.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC35XOguJdRr0O918kYLqrXhOCc42hUW-Y',
    appId: '1:64305981522:ios:986443b71ee204d5e8d78b',
    messagingSenderId: '64305981522',
    projectId: 'taskify-cb192',
    storageBucket: 'taskify-cb192.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGG60FR0bNFupLebZxgsbreT2LUVXl6V0',
    appId: '1:64305981522:web:fcf198f00b747abbe8d78b',
    messagingSenderId: '64305981522',
    projectId: 'taskify-cb192',
    authDomain: 'taskify-cb192.firebaseapp.com',
    storageBucket: 'taskify-cb192.firebasestorage.app',
    measurementId: 'G-V2X9494M9Y',
  );
}
